### PR TITLE
Hack fix

### PR DESCRIPTION
**Pull request by microwin7**

### CODE REVIEW

**Comment by Funwayguy** [comment]
and what would this be fixing exactly?

**Comment by microwin7** [comment]
Well, the fixes are not mine, but as I understand it, it prohibits sending a package from cheats

**Comment by microwin7** [comment]
you just need to check whether it will work, because I transferred only edits, without checking in idea

**Comment by microwin7** [comment]
(The link was deleted by me, the developer saw)

**Comment by Funwayguy** [comment]
I see... but why make so many separate PRs?

Guess I'll just reference these, recreate the changes locally, then push it as one commit locally.

PS: I'm a little pissed off about that hack but I'll add additional protections against this.

**Comment by microwin7** [comment]
Good. Thanks

**Pull request closed without merging**
