### PR TITLE
implement PermissionAPI on BetterQuesting command

### PR DESCRIPTION
**Pull request by Clem-Fern**
Hi, 
I tried to add permission management on the commands present in the mod.
It's actually quite complicated for server administrators to not be able to give permissions to moderators.

Example of permission : 
- betterquesting.command.user
- betterquesting.command.admin
- betterquesting.command.user.refresh
- betterquesting.command.admin.reset

I tested the different permissions using sponge and the LuckPerms plugin. At first sight, everything works.

Sorry for my rough english, I still have to work it :)

### CODE REVIEW

**Comment by Clem-Fern** [comment]
Some news ?

**Comment by Funwayguy** [comment]
Have been caught up working on other things and haven't taken time to go over this commit yet, sorry.

I mostly need to to ensure that this doesn't lower edit permission restrictions. Command rewards are as powerful as a server console operator.

**Comment by Clem-Fern** [comment]
No problem, I thought the request had fallen into oblivion.
Feel free to tell me if changes are needed :)

**Comment by Funwayguy** [comment]
Looks good from what I've checked.

Also thanks for also adding in that single player version of the hardcore command. Completely skipped my mind that it wasn't possible without cheats.

This will all be included in the next public build. Going to double check and play test some other things before then though.

**Pull request merged**
